apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrafeed
spec:
  replicas: 5
  selector:
    matchLabels:
      app: terrafeed
  template:
    metadata:
      labels:
        app: terrafeed
    spec:
      containers:
      - name: terrafeed
        image: us.icr.io/maheshsub/myrepo
        imagePullPolicy: Always
        ports:
        - containerPort: 8000