apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeless
spec:
  replicas: 5
  selector:
    matchLabels:
      app: codeless
  template:
    metadata:
      labels:
        app: codeless
    spec:
      containers:
      - name: codeless
        image: us.icr.io/nagi/myrepo
        imagePullPolicy: Always
        ports:
        - containerPort: 8000